POST http://localhost:4000/login
Content-Type: application/json

    {
    "username": "test",
    "password": "test"
    }

###
GET http://localhost:3001/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1MjQ1MzY2MCwiZXhwIjoxNjUyNDU3MjYwfQ.Ol5nIs6ofnAi6LRrI8ov9ktYq9jGahIY0iLT1jyoqcA

###
POST http://localhost:3001/addStudent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1MjQ1MzY2MCwiZXhwIjoxNjUyNDU3MjYwfQ.Ol5nIs6ofnAi6LRrI8ov9ktYq9jGahIY0iLT1jyoqcA
Content-Type: application/json
    
    {
        "id":82626,
        "name":"test",
        "classification":"test",
        "school":"test"
    }

###
POST http://localhost:3001/deleteStudent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1MjQ1MzY2MCwiZXhwIjoxNjUyNDU3MjYwfQ.Ol5nIs6ofnAi6LRrI8ov9ktYq9jGahIY0iLT1jyoqcA
Content-Type: application/json
    
    {
        "id":82626
    }

###
POST http://localhost:3001/editStudent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1MjQ1MzY2MCwiZXhwIjoxNjUyNDU3MjYwfQ.Ol5nIs6ofnAi6LRrI8ov9ktYq9jGahIY0iLT1jyoqcA
Content-Type: application/json
    
    {
        "id":82626,
        "name":"testss",
        "classification":"test",
        "school":"test"
    }
###
GET http://localhost:3001/getStudents
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1MjQ1MzY2MCwiZXhwIjoxNjUyNDU3MjYwfQ.Ol5nIs6ofnAi6LRrI8ov9ktYq9jGahIY0iLT1jyoqcA


###

GET http://localhost:3001/getStudentById?id=82626
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1MjQ1MzY2MCwiZXhwIjoxNjUyNDU3MjYwfQ.Ol5nIs6ofnAi6LRrI8ov9ktYq9jGahIY0iLT1jyoqcA
