POST http://localhost:4000/login
Content-Type: application/json

    {
    "username": "test",
    "password": "test"
    }

###
GET http://localhost:3001/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY0OTE1Mzg5OSwiZXhwIjoxNjQ5MTU3NDk5fQ.K3Z9ua9I54VnuEDfQxSTpUUHy86mnmj4kd9rwwqdnaE