POST http://localhost:4000/login
Content-Type: application/json

    {
    "username": "test",
    "password": "test"
    }

###
GET http://localhost:3001/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1MzY2NzY4MywiZXhwIjoxNjUzNjcxMjgzfQ.SKBVbjL86ruuvX8A2YsAbFUbMa1pe49S7h8yrWy5m7E

###
POST http://localhost:3001/api/student/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1MzY2Nzg4NywiZXhwIjoxNjUzNjcxNDg3fQ.OkGV1ctDYZYNZEE4I-Km3hxBTsfN9QKV1dm0sCKYjI4
    
    {
       "id": 1,
       "FullName": "test",
       "email": "test@test.com",
       "ResearchInterests": ["test","test2"],
       "experience":["test","test2"],
       "publications":["test","test2"],
       "CV": ["test","test2"]

    }

###
POST http://localhost:3001/api/student/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1MzY2ODQxMCwiZXhwIjoxNjUzNjcyMDEwfQ.qx2NONOVDwRrwoq0o0itA1Qy_arqpXVZV94F6RCEsuI

###
GET http://localhost:3001/api/student/get_id/82626
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1MzY2ODQxMCwiZXhwIjoxNjUzNjcyMDEwfQ.qx2NONOVDwRrwoq0o0itA1Qy_arqpXVZV94F6RCEsuI

###
POST http://localhost:3001/api/faculty/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1MzY2ODQxMCwiZXhwIjoxNjUzNjcyMDEwfQ.qx2NONOVDwRrwoq0o0itA1Qy_arqpXVZV94F6RCEsuI

    {
    "id": 1,
    "FullName": "test",
    "email": "test@etst.com",
    "Phone": "123456789",
    "OfficeHours":["Tueday 3pm-4","Wednesday 4-5"],
    "OfficeLocation":"test",
    "ResearchInterests":["test","test2"],
    "SelectedPublications":["test","test2"],
    "Description":"test"
    }

